<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-ICSBMB7" failures="2" tests="2" name="Default test(failed)" time="0.21" errors="0" timestamp="2021-07-07T13:04:40 IST">
  <testcase classname="_41_TestNG.Manual_Re_RunFailed_Tests.TestCases" name="TC_03" time="0.032">
    <failure type="java.lang.AssertionError" message="Failing TC_03">
      <![CDATA[java.lang.AssertionError: Failing TC_03
at _41_TestNG.Manual_Re_RunFailed_Tests.TestCases.TC_03(TestCases.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- TC_03 -->
  <testcase classname="_41_TestNG.Manual_Re_RunFailed_Tests.TestCases" name="TC_04" time="0.004">
    <failure type="java.lang.AssertionError" message="Failing TC_04">
      <![CDATA[java.lang.AssertionError: Failing TC_04
at _41_TestNG.Manual_Re_RunFailed_Tests.TestCases.TC_04(TestCases.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- TC_04 -->
  <testcase classname="_41_TestNG.Manual_Re_RunFailed_Tests.TestCases" name="TC_02" time="0.0">
    <ignored/>
  </testcase> <!-- TC_02 -->
  <testcase classname="_41_TestNG.Manual_Re_RunFailed_Tests.TestCases" name="TC_01" time="0.0">
    <ignored/>
  </testcase> <!-- TC_01 -->
</testsuite> <!-- Default test(failed) -->
